### ISSUE TITLE
QWAZR was not able to find the controller class

### ISSUE THREAD

**Issue by naveenann** [qwazr/qwazr-java-example#7]
Following the readme when trying to start the server using mvn -e qwazr:start it fails with class not found. Let me know if i am missing something.

Here is the full stack trace.

```
 ❯ mvn -e qwazr:start                                                                                                                                                                          [12:11:34]
[INFO] Error stacktraces are turned on.
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building QWAZR Quick-Start 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO]
[INFO] --- qwazr-maven-plugin:1.0.1:start (default-cli) @ java-maven-project ---
[INFO] Starting QWAZR
[INFO] Configuration (ETC) directory #1 : /Users/naveen/qwazr-java-example/etc
[INFO] PID obtained through native call to getpid(): 96408
[INFO] Server: http://192.168.1.200:9091 Groups: null
[INFO] Start Datagram listener http://192.168.1.200:9091
[INFO] Loading Web application
[INFO] Load library configuration file: /Users/naveen/qwazr-java-example/etc/conf.json
[INFO] Load WebApp configuration file: /Users/naveen/qwazr-java-example/etc/conf.json
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 01:57 min
[INFO] Finished at: 2016-11-23T12:13:35+05:30
[INFO] Final Memory: 25M/94M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal com.qwazr:qwazr-maven-plugin:1.0.1:start (default-cli) on project java-maven-project: Cannot start QWAZR: Cannot build an instance of the controller: com.qwazr.example.HomeServlet -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal com.qwazr:qwazr-maven-plugin:1.0.1:start (default-cli) on project java-maven-project: Cannot start QWAZR
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:212)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:862)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:286)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoFailureException: Cannot start QWAZR
	at com.qwazr.mavenplugin.QwazrStartMojo.execute(QwazrStartMojo.java:163)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: com.qwazr.utils.server.ServerException: Cannot build an instance of the controller: com.qwazr.example.HomeServlet
	at com.qwazr.webapps.WebappManager.registerController(WebappManager.java:193)
	at com.qwazr.webapps.WebappManager.lambda$new$1(WebappManager.java:142)
	at com.qwazr.webapps.WebappManager$$Lambda$21/953492906.accept(Unknown Source)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676)
	at com.qwazr.webapps.WebappManager.<init>(WebappManager.java:141)
	at com.qwazr.webapps.WebappManager.load(WebappManager.java:84)
	at com.qwazr.Qwazr.newServer(Qwazr.java:108)
	at com.qwazr.Qwazr.startWithConf(Qwazr.java:135)
	at com.qwazr.mavenplugin.QwazrStartMojo$Launcher.startEmbedded(QwazrStartMojo.java:258)
	at com.qwazr.mavenplugin.QwazrStartMojo$Launcher.access$100(QwazrStartMojo.java:167)
	at com.qwazr.mavenplugin.QwazrStartMojo.execute(QwazrStartMojo.java:159)
	... 22 more
Caused by: java.lang.ClassNotFoundException: com.qwazr.example.HomeServlet
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at com.qwazr.utils.ClassLoaderUtils.findClass(ClassLoaderUtils.java:26)
	at com.qwazr.webapps.WebappManager.registerJavaController(WebappManager.java:213)
	at com.qwazr.webapps.WebappManager.registerController(WebappManager.java:191)
	... 32 more
[ERROR]
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
>>> elapsed time 2m1s
 
```

**Comment by emmanuel-keller** [comment]
Thanks @naveenann 
Just fixed. You may try again. It should work now.

**Comment by naveenann** [comment]
Still having issues
```
INFO] Scanning for projects...
[WARNING] The POM for com.qwazr:qwazr-maven-plugin:jar:1.1-SNAPSHOT is missing, no dependency information available
[WARNING] Failed to retrieve plugin descriptor for com.qwazr:qwazr-maven-plugin:1.1-SNAPSHOT: Plugin com.qwazr:qwazr-maven-plugin:1.1-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact com.qwazr:qwazr-maven-plugin:jar:1.1-SNAPSHOT
Downloading: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml
Downloading: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml
Downloaded: https://repo.maven.apache.org/maven2/org/codehaus/mojo/maven-metadata.xml (20 KB at 4.0 KB/sec)
Downloaded: https://repo.maven.apache.org/maven2/org/apache/maven/plugins/maven-metadata.xml (13 KB at 2.3 KB/sec)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 8.252 s
[INFO] Finished at: 2016-11-23T21:38:57+05:30
[INFO] Final Memory: 11M/123M
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'qwazr' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/Users/naveen/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException
>>> elapsed time 16s
```

Added the plugin repository to pom file and it worked.

```
<pluginRepositories>
        <pluginRepository>
            <id>qwazr.snapshots</id>
            <name>QWAZR Snapshot Repository</name>
            <url>https://oss.sonatype.org/content/repositories/snapshots</url>
            <releases>
                <enabled>false</enabled>
            </releases>
        </pluginRepository>
    </pluginRepositories>
```

**Comment by emmanuel-keller** [comment]
It should be better now. Another attempt ?

**Comment by naveenann** [comment]
It worked.Looks awesome 👍
